    services:
  - type: web
    name: olu-blog-summarizer  # replace this with your actual service name
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000


